name: Validate Website Content
on:
  workflow_call:
    inputs:
      site_git_ref:
        description: 'git ref, a SHA commit or branch or tag, for the published HTML content'
        required: true
        default: 'nist-pages'
        type: string
      site_git_ref_path:
        description: 'the subdirectory to check out git ref and check links in website content'
        required: true
        default: 'published'
        type: string
      linkcheck_create_issue:
        description: 'create new GitHub issue if broken links found'
        required: false
        default: false
        type: boolean
      linkcheck_fail_on_error:
        description: 'create new GitHub issue if broken links found'
        required: false
        default: false
        type: boolean
jobs:
  schedule-validate-website-links:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      issues: write
    steps:
    - name: Checkout Latest
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0 # this ensures that the tag and commit history are available
    - name: Checkout git ref of published website content
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        ref: ${{ inputs.site_git_ref }}
        path: ${{ inputs.site_git_ref_path }}
    - name: Check website HTML content links
      id: linkchecker
      uses: lycheeverse/lychee-action@c3089c702fbb949e3f7a8122be0c33c017904f9b
      with:
        args: --exclude-file .github/workflows/config/.lycheeignore --verbose --no-progress --accept 200,206,429 './${{ inputs.site_git_ref_path }}/**/*.html' --exclude-mail
        fail: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
    - name: Create issue if bad links detected
      if: ${{ !cancelled() && env.lychee_exit_code != 0 && inputs.linkcheck_create_issue }}
      uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f
      with:
        title: Scheduled Check of Website Content Found Bad Hyperlinks
        content-filepath: ./lychee/out.md
        labels: |
          bug
          documentation
    - name: Check coverage tolerance
      if: ${{ env.lychee_exit_code != 0 && inputs.linkcheck_fail_on_error }}
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
      with:
        script: |
          core.setFailed('Link checker detected broken or invalid links, read attached report.')
